name: CML Report Workflow

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run main file
      run: |
        python main.py

    - name: Run Tests
      run: |
        python -m unittest discover

    # CML Part
    - name: Install CML
      run: |
        npm install -g @dvcorg/cml

    - name: Create CML report
      run: |
        echo "# Model Report" > report.md
        echo "## Bar Plots" >> report.md
        echo '![](./bar_chart.png "Bar plot")' >> report.md
        echo "## Line Plots" >> report.md
        echo '![](./line_plot.png "Line plot")' >> report.md

    - name: Post report as comment
      env:
        REPO_TOKEN: ${{ secrets.CI_PIPELINE }}
      run: |
        npx cml comment create report.md